### ISSUE TITLE
Something wrong, check and try again - adding SSH Key

### ISSUE THREAD

**Issue by Chaffy-0** [hap-wi/haproxy-wi#277]
I'm following along with the How to setup servers, group, and SSH credentials.  I've created my user on my haproxywi server as well as my target servers.  I've successfully copied the public key to each target and tested ssh from the haproxywi server with no password needed.  I'm at the part of the document where I add the SSH key.  I create the user, add it to the group I created, checked the box to enable SSH key, and saved the user.  I get the "Something wrong, check and try again." error when I try to save the SSH Key.  I'm selecting the user from the drop down and pasting the private key in the Key field.  

Does it matter what is in the credentials field?  In the doc I see it set to id_pub.  I generated a key as the ed25519 type and the file names are haprox_ed25519.  I've tried setting the credentials as haprox_ed25519, haprox_ed25519.pub, and id_pub but all 3 give me the same error.  I tried looking at the Internal logs option from the admin section but I don't see any log files.

**Comment by Aidaho12** [comment]
There is httpd error log, look through it too

**Comment by Chaffy-0** [comment]
Bingo!  not a valid private key file.  I have an OpenSSH file, does it need to be RSA?

**Comment by Aidaho12** [comment]
I haven't try anything except RSA. So, yes, maybe problem in that you use isn't RSA key

**Comment by Chaffy-0** [comment]
I ended up just using the username and password instead of the key for now.  I'll circle back around to play around with it later.  I appreciate your help!
