### ISSUE TITLE
No "Proxy installation" possible

### ISSUE THREAD

**Issue by klepptor** [hap-wi/haproxy-wi#278]
Hi!

I did a manuell install of HAProxy-WI 5.1.2.0 on an Ubuntu 20.04 VM as described [here](https://haproxy-wi.org/installation.py#manual) with some neccessary corrections as the docs are not very precise for Ubuntu.

Right now I've created a ssh user  and two servers I want to run as an HAProxy Cluster. But unfortunatly I can't install HAProxy:

{"changed": false, "msg": "Malformed output discovered from systemd list-unit-files: accounts-daemon.service enabled enabled "}

The file /var/log/apache2/error.log is emtpy about my install procedure

![image](https://user-images.githubusercontent.com/3921511/117684972-cd825600-b1b5-11eb-8361-8392ed65f3ac.png)

![image](https://user-images.githubusercontent.com/3921511/117684921-bfccd080-b1b5-11eb-87a6-c51b1b05b464.png)

Do you have any hint what could be wrong or were can I get more information about this? @Aidaho12  Seems to be an Ansible Problem!?

**Comment by Aidaho12** [comment]
Hi,

I think you have faced with this bug https://github.com/ansible/ansible/issues/68536

**Comment by klepptor** [comment]
Thx! Switched to Ubuntu 18.04 and now it works...
