### ISSUE TITLE
Not able to install GeoIP

### ISSUE THREAD

**Issue by xPakrikx** [hap-wi/haproxy-wi#279]
System info:

OS: Debian 10.9
HAproxy: 2.2.14-1~bpo10+1 (from haproxy debian repo)
HAproxy-wi : v5.1.2.0

I'm trying to install HAproxy-wi + HAproxy (ssh access over localhost...). First i think there is some errors in manual installation manual like example:  "chown -R apache:apache"  i think correct is "chown -R www-data:www-data". 

My HAproxy-wi is runnig with added server (localhost), for login i created user haproxy-wi and add him to suders
`haproxy-wi	  ALL=(ALL)	  NOPASSWD: ALL`
Then i added maxmind key for geoip in to the settings and tried install geoip on selected server. But there was problem with folder permissions. Permission deny  for creating folder in /var/www/.ansible/tmp. So i created folder var/www/.ansible/ and add  www-data as owner. Error is gone now and installation ends with success but when i reload settings i see "GeoLite2 has not installed". 

Any help how can i solve this problem ? I want to use allowlist based on geoip in haproxy

Very thanks for help

**Comment by Aidaho12** [comment]
Have you read this https://haproxy-wi.org/installation.py#ansible ?

**Comment by xPakrikx** [comment]
Yes, but instead `sudo chown apache:apache /usr/share/httpd/.*` i use `sudo chown www-data:www-data /usr/share/apache2/.*`

**Comment by Aidaho12** [comment]
Try to run the ansible playbook manually

**Comment by xPakrikx** [comment]
looks like there is a problem with path. 

`ansible.errors.AnsibleError: Unable to create local directories(/var/www/.ansible/tmp): [Errno 13] Permission denied: b'/var/www/.ansible/tmp' `

`File "/usr/lib/python3/dist-packages/ansible/utils/path.py", line 81, in makedirs_safe
--
File "/usr/lib/python3/dist-packages/ansible/config/manager.py", line 91, in ensure_type
File "/usr/lib/python3/dist-packages/ansible/config/manager.py", line 434, in get_config_value_and_origin
value = ensure_type(value, defs[config].get('type'), origin=origin)
raise AnsibleError("Unable to create local directories(%s): %s" % (to_native(rpath), to_native(e)))
makedirs_safe(value, 0o700)`

path for .ansible folder should be in /usr/share/apache2/.

Ok i try it

**Comment by xPakrikx** [comment]
Ok with manual edited /var/www/haproxy-wi/app/scripts/install_geoip.sh installation was successful. But there was one missing dependency for ansible, **sshpass**. I dont use ssh keys for login.

**Comment by Aidaho12** [comment]
Could you say what did you edit in the script?
And thanks for sshpass

**Comment by xPakrikx** [comment]
i just created a copy with new name install_geoip_manual.sh and deleted some conditions that i dont need ...

`!/bin/bash
PROXY=
UPDATE="1"
maxmind_key="MAXMINDKEY"
haproxy_dir="/etc/haproxy"
HOST="127.0.0.1"
USER="haproxy-wi"
PASS="HAPROXYPASS"
SSH_PORT="22"

export ANSIBLE_HOST_KEY_CHECKING=False
export ANSIBLE_DISPLAY_SKIPPED_HOSTS=False
export ACTION_WARNINGS=False
export LOCALHOST_WARNING=False
export COMMAND_WARNINGS=False

PWD=/var/www/haproxy-wi/app/scripts/ansible
echo "$HOST ansible_port=$SSH_PORT" > $PWD/$HOST

ansible-playbook $PWD/roles/geoip.yml -e "ansible_user=$USER ansible_ssh_pass=$PASS variable_host=$HOST PROXY=$PROXY UPDATE=$UPDATE haproxy_dir=$haproxy_dir maxmind_key=$maxmind_key SSH_$

if [ $? -gt 0 ]
then
        echo "error: Cannot download GeoLite2 database"
fi
rm -f $PWD/$HOST`

and then just run script from same folder

`sh install_geoip_manual.sh`

**Comment by Aidaho12** [comment]
Ok, I got it, thank you
